# Generated by Django 2.0 on 2019-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('chaptername', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nover',
            fields=[
                ('noverid', models.AutoField(primary_key=True, serialize=False)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('novername', models.CharField(blank=True, max_length=255, null=True)),
                ('writername', models.CharField(blank=True, max_length=255, null=True)),
                ('novelindex', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nover',
                'managed': False,
            },
        ),
    ]
