# Generated by Django 2.0 on 2019-02-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': False, 'ordering': ['chapterid']},
        ),
        migrations.AlterModelOptions(
            name='nover',
            options={'managed': False, 'ordering': ['noverid']},
        ),
    ]
