# Generated by Django 2.0 on 2019-02-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20190209_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nover',
            options={'managed': True, 'ordering': ['noverid']},
        ),
    ]
