# Generated by Django 2.0 on 2019-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20190211_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='nover',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
