# Generated by Django 2.0 on 2019-02-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_nover_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='nover',
            name='read_num',
        ),
        migrations.AddField(
            model_name='readnum',
            name='novel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='novel.Nover'),
        ),
    ]
