# Generated by Django 2.0 on 2019-02-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20190213_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='novel',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
