# Generated by Django 2.0 on 2019-02-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20190213_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': True, 'ordering': ['chapterid']},
        ),
    ]
