# Generated by Django 2.0 on 2019-02-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20190219_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': False, 'ordering': ['chapterid']},
        ),
        migrations.AlterModelOptions(
            name='nover',
            options={'managed': False, 'ordering': ['noverid']},
        ),
    ]
