# Generated by Django 2.0 on 2019-03-03 06:30

from django.db import migrations, models
import read_statistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20190220_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('novelname', models.CharField(blank=True, max_length=255, null=True)),
                ('writername', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'novel',
                'ordering': ['novelid'],
                'managed': True,
            },
            bases=(models.Model, read_statistics.models.GetReadNum),
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': True, 'ordering': ['chapterid']},
        ),
    ]
