# Generated by Django 2.0 on 2019-03-03 06:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20190303_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='novelid',
            field=models.ForeignKey(blank=True, db_column='novelid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='novel.Novel'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
