# Generated by Django 2.0 on 2019-03-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_auto_20190303_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'managed': True, 'ordering': ['-novelid']},
        ),
    ]
