# Generated by Django 2.0 on 2019-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190220_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
